### ISSUE TITLE
Return EventData.responseCode as number

### ISSUE THREAD

**Issue by henningn** [werpu/jsfs_js_ts#42]
I just discovered that the responseCode is returned as a string.
Shouldn't it be of type "number"? Because the value is from a XMLHttpRequest object and there it is of type 'number'.

https://github.com/werpu/jsfs_js_ts/blob/c342d17e79ef2bdcd164f2617c6142d4fd60c2b7/src/main/typescript/impl/xhrCore/EventData.ts#L23
https://github.com/werpu/jsfs_js_ts/blob/c342d17e79ef2bdcd164f2617c6142d4fd60c2b7/src/main/typescript/impl/xhrCore/EventData.ts#L43

**Comment by werpu** [comment]
I have to check that

**Comment by werpu** [comment]
Ja sieht so aus wie wenn ich hier falsch liege, da muss ich aber nochmal die spec checken,
im schlimmfsten fall ein parseint vorschieben!

**Comment by werpu** [comment]
Ist wirklich ein number kein string, mea culpa

**Comment by werpu** [comment]
fixed
