### ISSUE TITLE
Implement XMLHttpRequest upload property

### ISSUE THREAD

**Issue by henningn** [werpu/jsfs_js_ts#52]
The XMLHttpRequest has an upload property to track the progress of a file upload. There is currently no way to register an ProgressListener for an ajax file upload.

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/upload

In addition to faces.addOnEvent() and faces.addOnError() there should be a method like faces.addOnProgress().
In addition of faces.ajax.request(..., {onevent: ..., onerror: ...}) there should be a parameter like "onprogress".

**Comment by lofwyr14** [comment]
Alternative 1: the addOnEvent() registered function can be called with data.status === "progress"
Alternative 2: the addOnEvent() callback with data.status === "success" may contain a data.source === xhr: XMLHttpRequest and the programmer can register his listener in xhr.upload.onprogress 

What is the best? What says the Faces Spec.?
Alternative 2 is most flexible, but faces.addOnProgress() encapsulate the underlaying implementation.

**Comment by werpu** [comment]
In order not to break the faces spec I will add it as extension in the myfaces namespace, here is an example:
```json
 faces.ajax.request(document.getElementById("cmd_eval"), null,
            {
                render: '@form',
                execute: '@form',
                myfaces: {
                    onProgress: (event: ProgressEvent) => {
                        caughtProgressEvents.push(event);
                    }
                }
            });
```

**Comment by werpu** [comment]
Fix is in, see the Readme.md on how to use it!
